apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: localhost:5000/catalog-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env: 
        - name: ConnectionStrings__eventbus
          valueFrom: 
            configMapKeyRef: 
              name: all-env
              key:  ConnectionStrings__eventbus
        - name: ConnectionStrings__catalogdb
          valueFrom: 
            configMapKeyRef: 
              name: all-env
              key:  ConnectionStrings__catalogdb
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          valueFrom: 
            configMapKeyRef: 
              name: all-env
              key:  ASPNETCORE_FORWARDEDHEADERS_ENABLED
        - name: HTTP_PORTS
          valueFrom: 
            configMapKeyRef: 
              name: all-env
              key:  HTTP_PORTS   
        # - name: "DOTNET_ReadOnlyDataProtectionKeyDirectory"
        #   value: "/etc/dataprotection/"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  selector:
    app: catalog-api
  ports:
  - port: 80
    targetPort: 8080
