apiVersion: v1
kind: PersistentVolume
metadata:
  name: DOTNET_ReadOnlyDataProtectionKeyDirectory-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/dataprotection/
    type: DirectoryOrCreate
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: DOTNET_ReadOnlyDataProtectionKeyDirectory-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadOnlyMany
