apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels: 
    name: db-deploy
    app: python-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: db-pod
      app: python-app
  template:
    metadata:
      name: db
      labels:
        name: db-pod
        app: python-app
    spec: 
      containers:
        - name: db
          image: localhost:5000/db:latest
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: myapp
            - secretRef:
                name: dbsecret
          # env: 
          #   - name:  MYSQL_ROOT_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: dbsecret
          #         key: MYSQL_ROOT_PASSWORD
          #   - name:  MYSQL_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: dbsecret
          #         key: MYSQL_PASSWORD
          #   - name: MYSQL_DATABASE
          #     valueFrom:
          #       configMapKeyRef:
          #         name:  myapp
          #         key:  MYSQL_DATABASE
          #   - name: MYSQL_USER
          #     valueFrom:
          #       configMapKeyRef:
          #         name: myapp
          #         key: MYSQL_USER
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: pvc
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: pvc